### PR TITLE
Create linting GH workflow

### PR DESCRIPTION
**Pull request by tpluscode**
Drafting this until we merge #3

### CODE REVIEW

**Comment by amivanoff** [comment]
The linter will fail until the issue #7 resolution

**Comment by tpluscode** [comment]
We will wait as long as is necessary... but why #7?

**Comment by amivanoff** [comment]
awesome-lint checks repository tags, I guess. Like this
image

**Comment by tpluscode** [comment]
> The repository should have "awesome" as a GitHub topic

Can we fix this? @amivanoff

**Comment by VladimirAlexiev** [comment]
Closing, @amivanoff do you agree?

**Pull request merged**
